version: '2'
services:
    zookeeper:
        image: zookeeper:3.4
        container_name: zookeeper
        restart: always

    nimbus:
        image: storm:1.0.2
        container_name: nimbus
        command: storm nimbus
        depends_on:
            - zookeeper
        restart: always
        ports:
            - 6627:6627

    ui:
        image: storm:1.0.2
        container_name: ui
        command: storm ui
        depends_on:
            - nimbus
            - zookeeper
        restart: always
        ports:
            - 8080:8080

    supervisor:
        image: storm:1.0.2
        container_name: supervisor
        command: storm supervisor
        depends_on:
            - nimbus
            - zookeeper
        restart: always

    redis:
        image: redis:latest
        container_name: redis
        restart: always
        ports:
            - 6379:6379

networks:
  default:
    external:
      name: foo